version: '3.3'

services:
  db:
    image: library/postgres:12
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: news
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8020
    volumes:
      - .:/KyivTest
    ports:
      - "8020:8020"
    depends_on:
      - db
    links:
      - db

